#################################################
title: Today I Learned
url: https://baku753.github.io
author: baku753
description: 今日学んだこと
#################################################
copyright: baku753.github.io
icon: /asset/png/xxxxxxxx.png
analytics: xxxxxxxxxxxx
verification: xxxxxxxxxxxxxxxxxxxxxx
#################################################
# 基本設定
timezone: Asia/Tokyo
markdown_ext: "md"
theme: null
include: [_redirects]
permalink: :title
defaults:
#  -
#    scope:
#      type: "posts"
#    values:
#      permalink: :title
  -
    scope:
      path: "page"
    values:
      permalink: :basename
  -
    scope:
      path: "extra"
    values:
      permalink: :basename:output_ext
      layout: none
  -
    scope:
      path: "asset"
    values:
      layout: none
kramdown:
  input: GFM
  hard_wrap: true
  toc_levels: 1..2
plugins:
#  - jemoji
  - jekyll-optional-front-matter
  - jekyll-default-layout
#  - jekyll-titles-from-headings
optional_front_matter:
  remove_originals: true
#titles_from_headings:
#  strip_title: true